version: "2"

run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
  exclusions:
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - node_modules$
      - dist$
